apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    identifierl: carslabel
  name: cars-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cars-role
subjects:
- kind: ServiceAccount
  name: carssa
  namespace: carsproduction
